sudo: false
dist: trusty

language: scala

scala:
  - 2.11.11
  - 2.12.3
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: coveralls
      script: sbt coverage test coverageReport coveralls
      scala: 2.12.2
      jdk: oraclejdk8
